# -*- coding: utf-8 -*-
import uuid

from django.db import models

from django.utils.translation import ugettext_lazy as _


class SimpleModel(models.Model):
    """
    An abstract base class model that provides:
    self-updating 'created' and 'modified' fields.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    created = models.DateTimeField(
        verbose_name=_("created date"), null=True, auto_now_add=True
    )
    modified = models.DateTimeField(
        verbose_name=_("modified date"), null=True, auto_now=True
    )

    class Meta:
        abstract = True
        ordering = ("-created",)


class NamedModel(SimpleModel):
    """
    An abstract base class model that provides 'name' and
    autogenerated 'slug' fields.
    """

    name = models.CharField(
        verbose_name=_("Name"), max_length=255, null=True, blank=True
    )

    class Meta:
        abstract = True
        ordering = ("name",)

    def __str__(self):
        return self.name
