repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files
-     repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
        - id: flake8
          language_version: python3.7
-     repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
        - id: black
          language_version: python3.7
