
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vagrant
  | \.idea
  | _build
  | buck-out
  | build
  | dist
  | .env
  | .env.default
  | .bootstrap.sh
)/
'''
